Add tests for DailyPicturePresenter and solve some DI problems
moxy-community/Moxy pull request #115
Opened 2020-08-12 06:37 UTC by hram

2020-08-12 19:09 UTC, alaershov requested changes
Thanks for your contribution! There are quite a few issues I'd like to address before accepting your request, please look at the comments.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureFragment.kt
> +            presenter.onOpenBrowserError()
Not sure that should be delegated to presenter, I think it's not too mch of a logic to make that "presenter->view->presenter->view" ping-pong

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPicturePresenter.kt
> +    private val provider: CoroutineDispatcherProvider,
I'd avoid passing coroutine dispatcher or its factory to the presenter. It's a useless dependency that is used only in tests. The same effect could be achieved with https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/ . Simple code is good)

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureView.kt
> +    fun showImage(url: String)
You've changed the semantics of the View, and not in a good way IMO.

An example: `showImage` and `hideImage` are imperative-style, and they are not mutually exclusive. You can call  `showImage` and then `hideImage`. Rotate the screen, and these methods will be called again, both of them. You end up loading image, possibly even from the network, and immediately hiding this image.

That's why I had a single `showPicture` method, it represents the state of the View, and will not do any useless work.

The same could be said about show/hide copyright method. I consider any show/hide method pairs a bad practice, and prefer state-oriented presenters.

showImage and showVideo suffer from the same problem, both of them be called after screen rotation.

I agree with you on extracting the title, description and copyright methods, that's a good call. Please refactor show-hide methods to state versions, like showProgress, and think of something to improve showVideo/showImage situatiuon.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureView.kt
> +    fun setTitle(text: String)
Please also review the order of iew methods. It's a bit strange to have screen-specific methods and generic ones, like `showError` and `showProgress` mixed together.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/di/CoreModule.kt
> +    @Provides
Please use `@Binds` annotation, it's better in this case. If you have troubles with Dagger, let me know, I'll refactor it myself.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/di/InteractorModule.kt
> +    @Provides
same here, `@Binds` is your bro.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/util/AndroidLogger.kt
> +        android.util.Log.d(tag, msg)
why full qualified name instead of import?

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/util/ConsoleLogger.kt
> +class ConsoleLogger : Logger {
Maybe this class belongs in the test source set?

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/test/java/moxy/sample/BaseTest.kt
> +     * Предоставляет контекст с presenter и view, внутри которого можно выполнять проверки
Great class, but please use English in the comments) Also, why is this even a class? Looks more like a bunch of top-level functions.

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/test/java/moxy/sample/BaseTest.kt
> +    inline fun <P, reified V> createMockPresenterBlocking(
Couple questions:
1) why createPresenter and testState are suspending? Also surprised that mocking a suspending function actually works...
2) not sure that runBlocking is the best option here, maybe `runBlockingTest` suits better?

2020-08-12 19:09 UTC, alaershov commented on sample-app/src/test/java/moxy/sample/dailypicture/ui/DailyPicturePresenterTest.kt
> +        whenever(interactor.getPicture(null)).thenReturn(PictureOfTheDay(LocalDate.now(), url, title, description, copyright, PictureOfTheDay.MediaType.IMAGE))
this line is duplicated a lot, maybe refactor somehow?

2020-08-13 06:34 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureFragment.kt
> +            presenter.onOpenBrowserError()
Я не могу так свободно излагаться на английском. Простите меня за мой русский )
Это называется не ping-pong, а MVP
Если предлагать семпл приложения для библиотеки MVP то надо показывать как правильно применяется MVP
Тут уж извините моя принципиальная позиция.

В рамках вырожденного семпла это кажется как ping-pong
Достаточно в презентере добавить логирование ошибки и уже получается профит от MVP  - в тесте можно проверить, что ошибка была залогирвана

Могу добавить логирование в презентер

2020-08-13 06:35 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPicturePresenter.kt
> +    private val provider: CoroutineDispatcherProvider,
Огромное спасибо за замечание. Переделал как вы предложили, будет мне хорошим уроком.

2020-08-13 06:38 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureView.kt
> +    fun showImage(url: String)
Вы правы тут я проглядел.
Объединил функции анотацией AddToEndSingleTagStrategy в 2 группы

- tag = "show_hide_image" для функций которые отвечают за отображение картинки
- tag = "show_hide_copyright" для функций которые отвечают за отображение копирайта

2020-08-13 06:39 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureView.kt
> +    fun setTitle(text: String)
отсортировал и сгруппировал
не уверен, что правильно

2020-08-13 06:40 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/di/CoreModule.kt
> +    @Provides
переделал на @Binds и добавил аннотацию @Singleton

2020-08-13 06:42 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/util/AndroidLogger.kt
> +        android.util.Log.d(tag, msg)
спасибо что заметили
это я проглядел
хотел сначала сделат вариант логера как объекта с сигнатурой повторяющей стандартный логер
чтобы в коде не пришлось ничего переписывать для работы логера
но у дагера оказывается есть ограничение и он не может инжектить в object классы
когда переделал забыл поправить имена

2020-08-13 06:43 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/util/ConsoleLogger.kt
> +class ConsoleLogger : Logger {
всё верно, спасибо за замечание
перенес в тесты

2020-08-13 06:44 UTC, hram commented on sample-app/src/test/java/moxy/sample/BaseTest.kt
> +     * Предоставляет контекст с presenter и view, внутри которого можно выполнять проверки
с английским как я сказал у меня не очень
так что удалил комментарий )
и вынес в top-level функцию

2020-08-13 06:48 UTC, hram commented on sample-app/src/test/java/moxy/sample/BaseTest.kt
> +    inline fun <P, reified V> createMockPresenterBlocking(
убрал для createPresenter suspend кажется что теперь он не нужен
заменил на runBlockingTest если настаиваете )
все эти @ExperimentalCoroutinesApi не тянем на боевом проекте
если тут можно то прекрасно

2020-08-13 06:50 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureFragment.kt
> +            presenter.onOpenBrowserError()
Согласен, и протестировать поведение можно.

2020-08-13 06:52 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/ui/DailyPictureView.kt
> +    fun showImage(url: String)
Сложно выглядит, но для примера пусть будет) С копирайтом достаточно сделать текст нуллабельным, здесь тэг прям оверкилл.

2020-08-13 06:52 UTC, hram commented on sample-app/src/test/java/moxy/sample/dailypicture/ui/DailyPicturePresenterTest.kt
> +        whenever(interactor.getPicture(null)).thenReturn(PictureOfTheDay(LocalDate.now(), url, title, description, copyright, PictureOfTheDay.MediaType.IMAGE))
она не дублируется
это блок инициализации моков
кажется, что инициализация везде одинаковая но на самом деле в каждом тесте проверяется различные кейсы
в итоге мы проходим по всем веткам условных операторов и проверяем работу всех функций

в результате получаем 100% покрытие кода презентера
![изображение](https://user-images.githubusercontent.com/2150637/90103151-be679800-dd4a-11ea-8331-fb70c09ad456.png)

2020-08-13 06:59 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/domain/DailyPictureInteractorImpl.kt
> +class DailyPictureInteractorImpl
На самом деле, не очень понял, зачем вынесен интерфейс. Если для тестов - то почему используются моки, а не фейки? Если не для тестов - то для чего?

2020-08-13 07:00 UTC, alaershov commented on sample-app/src/main/kotlin/moxy/sample/util/CoroutineDispatcherProvider.kt
> +open class CoroutineDispatcherProvider {
Этот класс больше не нужен, кажется.

2020-08-13 07:00 UTC, alaershov requested changes
Поотвечал на комментарии, несколько ещё осталось.

2020-08-13 07:02 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/di/InteractorModule.kt
> +    @Provides
спасибо переделал на  `@Binds`

2020-08-13 07:07 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/domain/DailyPictureInteractorImpl.kt
> +class DailyPictureInteractorImpl
Все верно для тестов
Тесты пишутся на моках потому, что есть хорошие библиотеки которые позволяют легко мокировать необходимое поведение без создания фейков. стабов и тому подобного

2020-08-13 07:09 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/util/CoroutineDispatcherProvider.kt
> +open class CoroutineDispatcherProvider {
точно (
в тесте удали тут забыл
спасибо

2020-08-13 10:06 UTC, alaershov approved these changes
Ништяк получилось, спасибо за доработку)

2020-08-15 06:45 UTC, aasitnikov commented on sample-app/src/test/java/moxy/sample/dailypicture/ui/DailyPicturePresenterTest.kt
> +        whenever(interactor.getPicture(null)).thenReturn(PictureOfTheDay(LocalDate.now(), url, title, description, copyright, PictureOfTheDay.MediaType.IMAGE))
Склонен не согласиться - дублируется, и создаёт много визуального шума. Я предлагаю сделать метод, у которого будет куча дефолтных параметров (у нас же котлин), например:
```
private fun createPictureOfTheDay(
    date: LocalDate = LocalDate.of(2020, 3, 6),
    url: String = default_url,
    ....
): PictureOfTheDay = TODO()
```
А те тесты, которым нужны не дефолтные параметры, просто будут вызывать `createPictureOfTheDay(copyright = "")` например

2020-08-15 06:52 UTC, aasitnikov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/domain/DailyPictureInteractorImpl.kt
> +class DailyPictureInteractorImpl
Хочу вернуться к вопросу - зачем всё таки было выносить интерфейс интерактора? Как правило, у интеракторов/юзкейсов одна реализация. В тестах у нас используются библиотеки для моков, которым всё равно, интерфейс или нет. Реализация этого интерфейса живёт в том же модуле. Мне кажется, что создание интерфейса интерактора без причины в целом не очень хорошая практика, а в сэмпле-аппе тем более не нужна дополнительная сложность.

2020-08-15 06:58 UTC, aasitnikov commented
Получилось на сей момент 5 коммитов с сообщением "fixes after code review", может их все сквошнуть в один самый первый коммит?

2020-08-15 07:01 UTC, aasitnikov requested changes
Оставил несколько замечаний: про PictureOfTheDay, интерфейс интерактора и количество коммитов. А в остальном изменения позитивные, показывают как и зачем использовать стратегии с тегом, и как писать тесты на презентер.

2020-08-15 09:30 UTC, hram commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/domain/DailyPictureInteractorImpl.kt
> +class DailyPictureInteractorImpl
Видимо придется попотеть )

Если говорить о "причинах" и "как правило" то в текущем семпл проекте вот эти все интеракторы и репозитории сплошное излишество.

Если же есть желание поиграть в клин и показать как им пользоваться то надо понимать, что нужно показывать не "обычную" практику, а как должно быть в идеале. То есть надо понимать, что может быть несколько реализаций интеракторов.

Позвольте сошлюсь наверное на статью там много букв и все подробно расписано https://habr.com/ru/company/mobileup/blog/335382/ в "**Заблуждение: UseCase и/или Interactor**"
Раз уж любите дядю Боба то там и отсыл на него и дается определение интерактора "**Interactor – объект, который реализует use case**"

Это то что касается архитектур.

А теперь касаемо тестирования. Текущий ПР он в основном про тестирование и показывает какие были ошибки в зависимостях и как они должны решаться если конечно есть желание покрыть код тестами.

При тестировании вводится такое понятие как "class under the test" Так вот задача разработчика при написании теста реализовать прогнозируемое поведение зависимостей. Это достигается с помощью создания фейковых зависимостей (моков, стабов, фейков)

Если говорить про стабы и фейки я их не люблю (моё право) и никогда не использую потому что:
- их создание заставляет реализовывать все функции фейковой зависимости
- при неправильной реализации они могу сохранять свое состояние и аффектить тесты
- им сложно задать различные поведения в зависимости от значений входных параметров, придется внутри фейка реализовывать условную логику
- через них нельзя проверить как взаимодействовал с ними class under the test (не записываются действия)

Всеми этими недостатками лишены моки ну и огромное количество библиотек для облегчения мокирования которые позволяют легко создавать моки, управлять их поведением и записывать действия которые были произведены.

А теперь кратко:
- интерактор - это реализация интерфейса (обычно термин "реализация" относится к интерфейсу)
- все зависимости класса под тестом должны мокаться

2020-08-15 09:38 UTC, hram commented
> 
> 
> Получилось на сей момент 5 коммитов с сообщением "fixes after code review", может их все сквошнуть в один самый первый коммит?

пожалейте меня пожалуйста 
я почитал как это делается и ужаснулся
никогда не думал что кто то этим пользуется
на то они и коммиты чтоб по ним была история

2020-08-15 09:39 UTC, hram commented on sample-app/src/test/java/moxy/sample/dailypicture/ui/DailyPicturePresenterTest.kt
> +        whenever(interactor.getPicture(null)).thenReturn(PictureOfTheDay(LocalDate.now(), url, title, description, copyright, PictureOfTheDay.MediaType.IMAGE))
@aasitnikov поправил

2020-08-15 10:19 UTC, aasitnikov commented on sample-app/src/main/kotlin/moxy/sample/dailypicture/domain/DailyPictureInteractorImpl.kt
> +class DailyPictureInteractorImpl
Согласен со всем, кроме того, что интерактор - это реализация интерфейса, и что может быть несколько реализаций интеракторов. 

За много лет я ни разу не встречал ситуации, когда был интерфейс юзкейса\интерактора и у него было несколько реализаций. Можно ли считать выделение интерфейса интерактора некой "идеальной" практикой? Безусловно. 
Есть ли в этом хоть какой-то практический смысл? Никакого. Иногда, кончено, бывают ситуации, когда это нужно делать, но в этом сэпмл-аппе таких ситуаций нет. По той же логике можно выделять, например, интерфейс презентера, но этого почти никто не делает, потому что это бессмысленно.

При этом ни разу не видел, чтобы где-то утверждалось, что юзкейс или интерактор - это интерфейсы. То, что **Interactor – объект, который реализует use case**, не значит, что use case - это интерфейс, который интерактор должен реализовать. В той же статье написано, что **use case - это описание действия** - отсюда можно сделать вывод, что интерактор - это объект, который реализует это действие, а не какой-то интерфейс.

2020-08-15 10:28 UTC, aasitnikov commented
> на то они и коммиты чтоб по ним была история

Вообще да, но с исторической точи зрения какую информацию несет, например, третий коммит "fixes after code review"? Никакой полезной. Можно было бы оставить один коммит со всеми фиксами, это норм. 
Способов есть много - `git rebase -i` самый удобный, `git reset --soft HEAD~5 && git commit` самый быстрый

2020-08-21 04:58 UTC, aasitnikov commented
@hram Евгений, там остался один последний вопрос по интерактору, давайте определимся с ним и вмёржим PR

2020-08-25 00:09 UTC, hram commented
> 
> 
> @hram Евгений, там остался один последний вопрос по интерактору, давайте определимся с ним и вмёржим PR

Добрый день. Простите только сегодня заметил сообщение. Я не совсем понял, что за вопрос остался по интерактору. Если по поводу интерфейса так я постарался подробно и аргументировано отстоять свою позицию. Дальше аргументировать у меня нет желания.

Я предложил своё видение решения проблемы. Моё мнение не изменилось. Если не устраивает ПР то в этом нет ничего плохого. Я удалю его или если у вас есть такая возможность можете сами удалить.

2020-08-25 05:44 UTC, aasitnikov approved these changes

2020-08-25 05:44 UTC, merged